DELIMITER $$

DROP PROCEDURE IF EXISTS miCursor $$
CREATE PROCEDURE miCursor()
BLOCK1: BEGIN

	DECLARE FINISHED INTEGER DEFAULT 0;

	DECLARE ID INT;
    DECLARE NOMBRE VARCHAR(100);
    DECLARE AP_PATERNO VARCHAR(100);
    DECLARE AP_MATERNO VARCHAR(100);
    DECLARE FECHA_NAC DATE;
    DECLARE FECHA_ALTA DATE;
    
    DECLARE CLIENTES_CURSOR CURSOR FOR SELECT * FROM OPERATIVA.OP_CLIENTES;
    
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
    
	OPEN CLIENTES_CURSOR;
    
    obtenerDatos: LOOP 
			FETCH NEXT FROM CLIENTES_CURSOR INTO ID, NOMBRE, AP_PATERNO, AP_MATERNO, FECHA_NAC, FECHA_ALTA;
			IF FINISHED <> 0 THEN
							LEAVE obtenerDatos;
			END IF;
			
			INSERT INTO DATA_WAREHOUSE.DW_CLIENTES (
			CLI_ID,
			CLI_NOMBRE,
			CLI_AP_PATERNO,
			CLI_AP_MATERNO,
			CLI_FECHA_NAC,
			CLI_FECHA_ALTA
			)
			
			VALUES (ID,NOMBRE, AP_PATERNO, AP_MATERNO, FECHA_NAC, FECHA_ALTA);
            
		END LOOP obtenerDatos;
	CLOSE CLIENTES_CURSOR;
END BLOCK1;

$$

DELIMITER ;


SELECT * FROM DATA_WAREHOUSE.DW_CLIENTES;
DELETE FROM DATA_WAREHOUSE.DW_CLIENTES WHERE CLI_ID > 0;

SELECT * FROM OPERATIVA.OP_CLIENTES;
        
CALL miCursor();   

SELECT * FROM DATA_WAREHOUSE.DW_CLIENTES; 

-- DROP TABLE OPERATIVA.OP_CLIENTES;
-- DROP TABLE DATA_WAREHOUSE.DW_CLIENTES;